name: build_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: tanmancan/action-setup-ssh-agent-key@1.0.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Build
      run: 
        swift build -v
    - name: Run tests
      run: swift test -v
