name: build_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      env:
        publickey: ${{ secrets.DEPENDENCY_SSH_PUBLIC_KEY }}
      run: 
        ssh-add publickey
        swift build -v
    - name: Run tests
      run: swift test -v
